name: nui
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  dio: ^5.7.0
  path: ^1.9.0
  process_run: ^1.1.0
dev_dependencies:
  lints: ^5.0.0

executables:
  nui: 